---
- name: Create webroot
  become: yes
  file:
    state: directory
    path: /var/www/
    owner: root
    group: root
    mode: 0755

- name: Check if WordPress directory exists in /var/www
  become: yes
  stat: path=/var/www/{{server_hostname}}
  register: check_path

- name: Download WordPress
  become: yes
  get_url:
    url: https://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest: /tmp/wordpress-{{ wp_version }}.tar.gz
    checksum: "sha1:{{ wp_sha1sum }}"
  when: not check_path.stat.exists

- name: Extract WordPress
  become: yes
  unarchive:
    src: /tmp/wordpress-{{ wp_version }}.tar.gz
    dest: /tmp
    owner: www-data
    group: www-data
    copy: no
  when: not check_path.stat.exists

- name: Move WordPress install files
  become: yes
  command: mv /tmp/wordpress /var/www/{{server_hostname}}
  when: not check_path.stat.exists

- name: Fetch random salts for WordPress config
  become: no
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"

- name: Add wp-config
  become: yes
  template: "src=wp-config.php dest=/var/www/{{server_hostname}}/wp-config.php"

- name: Update WordPress config file
  become: yes
  lineinfile:
    dest: "/var/www/{{server_hostname}}/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_db_name}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_db_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_db_password}}');"}

- name: Add Upload max in htaccess
  become: yes
  template:
    src: "htaccess.tmp"
    dest: "/var/www/{{server_hostname}}/.htaccess"
    owner: www-data
    group: www-data
