---
- name: Install mysql
  become: yes
  with_items: "{{ ubuntu_mysql_packages }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: Start the MySQL service
  service:
    name: mysql
    state: started

- name: Set root user password
  become: yes
  become_user: root
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials
  become: yes
  become_user: root
  template:
    src: roles/mysql/templates/.my.cnf
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: Create mysql user
  become: yes
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "*.*:ALL"

- name: Create mysql database
  become: yes
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Delete anonymous MySQL server user for $server_hostname
  become: yes
  action: mysql_user user="" host="{{ server_hostname }}" state="absent"

- name: Delete anonymous MySQL server user for localhost
  become: yes
  action: mysql_user user="" state="absent"

- name: Remove the MySQL test database
  become: yes
  action: mysql_db db=test state=absent

- name: Update mysql root password for all root accounts
  become: yes
  mysql_user: name=root host={{ server_hostname }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
